### ISSUE TITLE
How to verify by mobile call

### ISSUE THREAD

**Issue by buiminhhuy** [Vonage/vonage-node-sdk#113]
How do to send verify code via mobile call to end user

**Comment by leggetter** [comment]
[Verify](https://docs.nexmo.com/verify/api-reference) will send a text message and fallback to making a TTS call that reads out the pin code. If you _only_ want to do this via a call then you would need to implement your own workflow.

That would flow may be [making a call](https://github.com/Nexmo/nexmo-node#make-a-call) to the target number and then using [talk](https://docs.nexmo.com/voice/voice-api/ncco-reference#talk) to read out the pin code numbers. You'd then want to store the pin code so that when the user enters the pin, that has been read out in the `talk`, you can check the pin is correct.

There's a blog post on [making a text-to-speech call with Node.JS](https://www.nexmo.com/blog/2017/01/12/make-outbound-text-speech-phone-call-node-js-dr/) that should also be of help.
