### ISSUE TITLE
How to send audio back through a websocket connection?

### ISSUE THREAD

**Issue by phil-andrews** [Vonage/vonage-node-sdk#124]
I'm having trouble getting audio to play when sent back through a websocket connection. The best I've gotten so far is a short crackle. It's receiving the file but not playing it, at least not correctly. I've tried to model the incoming websocket `binaryData` by sending back the audio in chunks of 640 bytes as that's what I've found the chunk size I receive to be.

```
wsServer.on('connect', (connection) => {

	const testFilePath = __dirname + '/sounds/test3.wav'

	// highWaterMark is set to the size of messages that the websocket receives from Nexmo
	const rStream = fs.createReadStream(testFilePath, { highWaterMark: 1*640 })
	rStream.on('data', (chunk) => {
		connection.sendBytes(chunk)
	})

})
```

I've tried both mp3 and wav formats. And wav in many different configurations that mimic telephony audio formats. Any guidance on this?

**Comment by sammachin** [comment]
Hi Phil,

This is a common problem, you need to send back the audio frames at appropriate intervals otherwise it just all plays out at once which is the crackle you are hearing. There's an issue on our roadmap to increase the buffer our end to around 10-30s.
Add a delay of 18ms between each each 640byte audio frame (the frame duration is 20ms, but if you set your delay to be that then you end up with gaps because there is a couple of ms of network jitter so I've found 18 or 19ms to be best.

You are correct in sending WAV (or RAW PCM Audio to be exact, WAV has a short header but that doesn't cause a problem) It should be 16bit 16Khz Mono with a 20ms frame size, at 16Hkz each 20ms frame will contain 320 samples of 16bits each so that give you the 640byte length.

**Comment by phil-andrews** [comment]
Oh wow, that worked perfectly. 19ms was dead on. Found 18 or 20 to have a slight chop.

**Comment by yeinel** [comment]
@phil-andrews  could you help me sharing the final example !? I am new with nexmo and websockets!

**Comment by kishoreacesurf** [comment]
How to save the buffer to audio file ? what will be the format
ws.on('message', function incoming(message) {
        if (typeof message === 'string') {
            // Reflect the message back
            console.log(message);
        }
        else{
            buffer = Buffer.concat([buffer, message]);
            // Reflect the message back
            ws.send(message);
        }
    });

**Comment by sammachin** [comment]
@kishoreacesurf This issue is closed so generally its not a good idea to post new questions on closed issues for unrelated threads. 

However you might want to take a look at the Audiosocket Framework example app in https://github.com/nexmo-community/audiosocket_framework This will do what you are asking, its in Python but maybe you can use that or port it over?

**Comment by hgezim** [comment]
@sammachin @phil-andrews How do I set the 20 ms delay in node?

**Comment by sammachin** [comment]
@hgezim this shouldn't be required any longer since an update to the interface means you can send your audio as fast as you like and we will buffer it our end.

**Comment by Rotorsoft** [comment]
Hi Sam. Do you have some sample code to share showing how to stream an mp3 file to the websocket? I'm trying to record the entire conversation and when the audio is streamed via the api (calls.stream...) it doesn't get picked up by the recorder nor it's streamed back through the socket (I guess that's the intended functionality). Thanks for your help!
