### ISSUE TITLE
how to send chinese text sms ?

### ISSUE THREAD

**Issue by jinwyp** [Vonage/vonage-node-sdk#138]
Hi all:
When I send chinese text “'A text message sent using the Nexmo SMS API 你好吗”， then got message on phone “A text message sent using the Nexmo SMS API ????” ,

```
exports.sendSms = function (sender, recipient, message) {

    sender = sender || 'Nexmo'
    recipient = recipient || '8613564568304'
    message = message || 'A text message sent using the Nexmo SMS API 测试短信'

    const options = {}

    return new Promise(function(resolve, reject) {

        nexmo.message.sendSms(sender, recipient, message, options, function (err, data) {
            if (err){
                reject(err)
            }
            resolve(data)
        })
    });
    
}

```

I find that there is a "type" parameters,  https://developer.nexmo.com/api/sms#parameters.

But how to set "type" to "unicode" using this nexmo-node ?

**Comment by mheap** [comment]
Hi @jinwyp,

To send chinese characters, you will need to tell Nexmo to treat your message as unicode. To do this, change `const options = {}` to `const options = {"type": "unicode"}`.

If you enable this option, each SMS you send will only be able to contain a maximum of 70 characters (rather than the 160 characters that a standard SMS allows). This is due to how the character encoding works. You can read more about character encoding on the [Nexmo developer portal](https://developer.nexmo.com/messaging/sms/guides/global-messaging#encoding).

Please let us know if you have any other issues.

Thanks, Michael

**Comment by jinwyp** [comment]
Is that mean I  still need  encode the message like below ? 


```
message = message || 'A text message sent using the Nexmo SMS API 测试短信'

nexmo.message.sendSms(sender, recipient, encode(message) , options, function (err, data) {
            if (err){
                reject(err)
            }
            resolve(data)
        })

```

**Comment by mheap** [comment]
Based on my test, you don't need to encode the message like you show

**Comment by jinwyp** [comment]
Many Thanks. It works
