### ISSUE TITLE
error-code': '420', 'error-code-label': 'method failed

### ISSUE THREAD

**Issue by bharathvaj-ganesan** [Vonage/vonage-node-sdk#193]
`nexmo.number.getPhonePricing('sms', 'IN', (result) => {
       console.log(result);
});`

**Response**
result => 
{ body: { 'error-code': '420', 'error-code-label': 'method failed' },
  headers:
   { server: 'nginx',
     date: 'Mon, 25 Jun 2018 04:57:32 GMT',
     'content-type': 'application/json;charset=UTF-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'x-frame-options': 'deny',
     'x-xss-protection': '1; mode=block;',
     'strict-transport-security': 'max-age=31536000; includeSubdomains',
     'content-disposition': 'attachment; filename="api.txt"',
     'x-nexmo-trace-id': '65973a5074a68d5d7ebb72b8510b21c2' },
  statusCode: 420 }
I'm getting the above as result even though arguments to that function is correct.

**Comment by AlexLakatos** [comment]
I'm sorry, there was an issue in the docs. The method statement for `getPhonePricing` requires a MSISDN instead of a country code. `getPricing` works with a country code. You can take a look at the example to see how it works: https://github.com/Nexmo/nexmo-node/blob/7142a0ccb6532cce7aeb4f65a6c40caeb4546710/examples/ex-number-pricing.js
