### ISSUE TITLE
HTTP request body truncated

### ISSUE THREAD

**Issue by mheap** [Vonage/vonage-node-sdk#196]
When making a `PUT` request with a body that contains UTF-8 characters, the existing HTTP client doesn't seem to send all of the data.

e.g. Sending `{"text":"¿Cómo te llamas?"}` results in `{"text":"¿Cómo te llamas?` being sent to the server

There are two missing characters at the end, and two non-ascii characters in the payload (`¿` and `ó`) which leads me to believe that it's encoding related

**Comment by ferk6a** [comment]
Indeed, it is a real bug. I just checked out the source code and found it:
https://github.com/Nexmo/nexmo-node/blob/5a181611b327d730e163cd5f55c77a25c6cfe675/src/StreamResource.js#L30-L39

`Content-Length` is wrong, it's being counted by a string, in "JavaScript codepoints" (a bit weird, not exactly UTF-8 because of surrogate pairs). I will fill a pull request to fix it tomorrow.
