### ISSUE TITLE
Post to nexmo using only Javascript.

### ISSUE THREAD

**Issue by diamanthaxhimusa** [Vonage/vonage-node-sdk#204]
Hello, is it possible to work with Nexmo with Javascript without using NodeJs? Thanks.

**Comment by AlexLakatos** [comment]
There is a client side JavaScript SDK for one of the Nexmo APIs: https://developer.nexmo.com/stitch/overview. But that still requires a server component with Node.

**Comment by diamanthaxhimusa** [comment]
@AlexLakatos So there is no way i can make it work without throwing me an error while posting with ajax?  I am using Nexmo in my PHP project, but i still need to work with javascript

**Comment by AlexLakatos** [comment]
Technically, you can, it's a REST API. But since you have to authenticate the request in the process, that would mean compromising and publishing your API key and secret in the client for anyone to see and we strongly advise against it.
Can you tell me more about your use case please? You should be able to use only PHP without needing JavaScript for it.

**Comment by diamanthaxhimusa** [comment]
@AlexLakatos I am using PHP to send the verification code and Javascript Ajax to verify it. But I am facing problems with mimetype when using Ajax get {dataType: 'jsonp'}, it throws error for mimetype, but the code is sent to the device. It returns me this error: 
`Refused to execute script from 'https://api.nexmo.com/verify/json?callback=jQuery2110883670313380436_1538083025686&brand=xxxx&api_key=xxxx&api_secret=xxxx&number=xxxx&_=xxxx' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`
