### ISSUE TITLE
Throughput Rate Exceeded error

### ISSUE THREAD

**Issue by danilvalov** [Vonage/vonage-node-sdk#33]
Hi.
All our accounts are set with 30 SMS per second cap. Except US and Canada with long virtual numbers limited to 1 SMS per second. Or we'll see:

```
Throughput Rate Exceeded - please wait [ 978 ] and retry
```

About it: https://help.nexmo.com/hc/en-us/articles/203993598-What-is-the-Throughput-Limit-for-Outbound-SMS-
Please, add support of queue for sending sms.

Thank you.

**Comment by sma2027** [comment]
Hi, I have a wait of 1 sms in my code for a long number but still get this error message.  please advise.

**Comment by leggetter** [comment]
Hi @danilvalov (really sorry for the crazy delay you've seen to get a reply). Hi @sma202.

I'm sorry to say that this isn't something related to nexmo-node. It's an error response from the API and thus a platform question. The best way to get an answer to this question is by email support@nexmo.com. That's because they can look at your account and work out why you may be seeing this error.

**Comment by ThoseGuysInTown** [comment]
Do you guys provide (or recommend) any solutions to be able to que up requests to nexmo? I'm setup so that on an individual request the requests to nexmo won't exceed 1 per second however if I have multiple threads running multiple of these requests I get the "Throughput Rate Exceeded - please wait [ 993 ] and retry" message. 

Thanks
