### ISSUE TITLE
Voice Types

### ISSUE THREAD

**Issue by kellyjandrews** [Vonage/vonage-node-sdk#364]
Create typings for Voice API

**Comment by peppermint-juli** [comment]
Hello! I would like to work on this issue! What is the expected result? I saw the similar issue #363 but I still don't know what should be done, add a an interface in index.d.ts file? what exactly are the types?

**Comment by kellyjandrews** [comment]
Hey @PeppermintNDaisies - thanks for the offer.  Take a look at https://github.com/Vonage/vonage-node-sdk/pull/372 for a good example of what we are after.  The types are in the API reference - https://developer.nexmo.com/api/voice

**Comment by peppermint-juli** [comment]
Perfect, thanks! I'll start working on this

**Comment by peppermint-juli** [comment]
Hello @kellyjandrews! I submitted a PR for this issue #379, I hope it helps, I tried my best to abstract the Voice API types and follow the code style of the project in order to get it right. If there's something wrong or that needs to be changed (or something I didn't get right) let me know and I'll do my best to fix it.

**Comment by kellyjandrews** [comment]
@PeppermintNDaisies Thanks for the submission - I'll be reviewing this soon.
