### ISSUE TITLE
Add way to generate JWT with App ID and Key to be used from outside module

### ISSUE THREAD

**Issue by cbetta** [Vonage/vonage-node-sdk#68]
This is needed for Nexmo/nexmo-cli#88 

@leggetter you already added a `JwtGenerator` but I can't use this from the CLI as it's not being exported yet by the module. What do you reckon we do, export the class or an instance?

**Comment by cbetta** [comment]
Secondly: add it as a instance on a nexmo client, or as a separate export to be used separately.

Option 1:

``` js
import Nexmo from 'nexmo';
let nexmo = new Nexmo(...);
nexmo.jwt.generate(appId, keyFile);
// alternative B
nexmo.jwtGenerator.generate(appId, keyFile);
```

Option 2 

``` js
import { JwtGenerator } from 'nexmo';
let generator = new JwtGenerator();
generator.generate(appId, keyFile);
```

**Comment by leggetter** [comment]
The following will work:

``` js
nexmo.credentials.generateJwt();
```

As will the following to override the used application ID:

``` js
nexmo.credentials.generateJwt(appId)
```

We could allow a `privateKey` to be passed in.

But I think we ultimately just want to generate a JWT from any applicationId and PrivateKey combination. So we should probably aim for one of:

``` js
nexmo.generateJwt(appId, privateKey);

// or as a static

Nexmo.generateJwt(appId, privateKey);
```

@tjlytle - see this comment and the one before. What do you think?

_Note: I'm not sure about the `KeyPair` approach right now since the Public Key is never used._

**Comment by cbetta** [comment]
@leggetter mind educating me why currently there's a function to create a JWT that takes an app ID but not a private key? Aren't these linked? Every time I generate an app I get a new App ID and key, right?
