### ISSUE TITLE
Some typescript types are wrong

### ISSUE THREAD

**Issue by maximelebastard** [Vonage/vonage-node-sdk#742]
## Expected Behavior
I follow the documentation and the types to implement Vonage SMS sendings. I'd like to rely on them.
I have two basic examples that don't work:

A/ The Authentication

The getting started on the console is the following to send a basic SMS

<img width="975" alt="Capture d’écran 2022-11-24 à 15 36 42" src="https://user-images.githubusercontent.com/6564357/203812500-dd411070-f1bd-41f5-932b-3a017f1fb968.png">

Therefore, I expect the constructor type to look like this - with only apiKey and apiSecret to be required

```
export declare class Vonage {
    constructor(credentials: AuthInterface);
}

export interface AuthInterface {
    apiKey: string;
    apiSecret: string;
    signature?: SignedHashParams;
    applicationId?: string;
    privateKey?: string;
    getQueryParams<T>(params?: T)?: AuthQueryParams & T;
    createSignatureHash<T>(params: T)?: AuthSignedParams & T;
    createBasicHeader()?: string;
    createBearerHeader()?: string;
}
```

B/ The response of the sending

I'd like to get a sending ID after I've sent the SMS, and I saw this type for the sms.send response
```
export interface SendSMSResponse {
    'message-count': string;
    messages: Message[];
}
export interface Message {
    to?: string;
    messageId?: string;
    status?: string;
    remainingBalance?: string;
    messagePrice?: string;
    network?: string;
    clientRef?: string;
    accountRef?: string;
}
```

Therefore, I expect to be able to use `res.messages[0].messageId` to get my the message ID I need

## Current Behavior

A/ The Authentication

If I bascially try your example, I get the following error

```
Argument of type '{ apiKey: string; apiSecret: string; }' is not assignable to parameter of type 'AuthInterface'.
  Type '{ apiKey: string; apiSecret: string; }' is missing the following properties from type 'AuthInterface': getQueryParams, createSignatureHash, createBasicHeader, createBearerHeaderts(2345)
```

This is because all the methods are indeed required in your definition.

B/ The response of the sending

The case of your type is wrong
```
messages?.[0].messageId // = undefined
messages?.[0]["message-id"] // = my message ID
```

Fortunately, I had some unit tests to spot that and it didn't go to production like that

## Potential solutions

I will probably check every of the types you provide, and put some `any` casts anywhere they're not right.
But these are very basic examples, it makes me consider your typescript definitions cannot be trusted - which is very annoying.

## Steps to Reproduce (for bugs)

Try your Getting Started for sending an SMS using TS, and to read the response.

## Context

I'd like to rely on Vonage to send SMS and maybe later use other features. But these basic errors make me doubtful about the reliability of the service.

## Your Environment
* SDK Version: @vonage/server-sdk@3.0.9
* Node Version: (e.g. Node 10.18): v14.19.0

**Comment by maximelebastard** [comment]
I'd like to add that on the console, the method to use to send an SMS is

```ts
vonage.message.sendSms("MySender", "+331122334455", "My message")
```

this method does not exists in this library.

The proper method to use seems to be

```ts
vonage.sms.send({
      from: "MySender",
      to: "+331122334455",
      text: "My message"
})
```

Maybe the console should provide a link to the repository for better accuracy of the documentation ? :)

**Comment by dragonmantank** [comment]
Sorry about this. The code snippets on the dashboard are supposed to update automatically, but they don't seem to be anymore. I'll reach out to our dashboard team to see what needs to be fixed. The getting started examples are for JavaScript and not TypeScript, so there are some things that the snippets allow you to do in JS that may be different in TS.

The current code snippet is: https://github.com/Vonage/vonage-node-code-snippets/blob/master/sms/send.js

**Authentication**

If you are using TypeScript, the typings are a bit more strict than what JavaScript will let you get away with. You will need to pass an `Auth` class to the constructor instead of an object that contains the credentials.

```js
const { Auth } = require('@vonage/auth');
const { Vonage } = require('@vonage/server-sdk');

const vonage = new Vonage(new Auth({
    apiKey: API_KEY,
    apiSecret: API_SECRET,
    applicationId: APP_ID,
    privateKey: PRIVATE_KEY_PATH,
  }), options);
```

If you are using JavaScript, you can send a raw object with the basic info like key, secret, appID, etc, and we'll do some swapping around to make it work, but for TypeScript it is more strict about what we allow to be passed in.

**SMS Response**

We will take a look at updating that definition so that is correct, so I'll leave this ticket open for the moment.

**Comment by dragonmantank** [comment]
@maximelebastard These definitions are corrected in the latest release. I kept the unmodified versions in and marked them as deprecated so you shouldn't have to change any code, unless your compiler complains about using deprecated properties.
