### ISSUE TITLE
shortcodeAlert: confusing parameters (messageParams and opts)

### ISSUE THREAD

**Issue by ale2805** [Vonage/vonage-node-sdk#76]
Hi, 
what is messageParams? 

Thanks

**Comment by cbetta** [comment]
@ale2805 thanks for the question. I had a quick look and as far as I can see `opts` and `messageParams` are the same thing. See https://github.com/Nexmo/nexmo-node/blob/master/src/index.js#L143-L166. @pvela any idea why these seem to be the same?

Now, the documentation for these options can be found on https://docs.nexmo.com/messaging/us-short-codes-api/event-based-alerts/send-event-based-alerts/api-reference#request. I'd use the `messageParams` instead of `opts` for now until @pvela can get to the bottom of this.

**Comment by mheap** [comment]
Reading the code and the documentation, I imagine that `opts` and `messageParams` have been separated so that you can easily see which parameters are needed by Nexmo (`opts`) and which parameters have been supplied for use in a template (`messageParams`).

Due to the way the Nexmo API works, both of these entires get merged together before sending the request, so this interface is purely for the user.

Here's an example to illustrate:

Given the following template:

```
Your ${server} is down, for more details check ${link} 🔥 
```

You can use the following method call (notice how Nexmo parameters and template parameters are separate):

```
nexmo.message.shortcodeAlert(
  'TO_NUMBER',
  {
    'status-report-req': 1, // Get a delivery receipt
    'type': 'unicode', // We're sending emoji!
  },
  {
    'server': 'example.com',
    'link': 'http://mybugreport.example.com/123-ABC'
  }
);
```
