### ISSUE TITLE
Error: secretOrPrivateKey must be an asymmetric key when using RS256

### ISSUE THREAD

**Issue by szyrelle290612** [Vonage/vonage-node-sdk#789]
after install this package I encounter this error
![image](https://user-images.githubusercontent.com/67720919/214399474-a13e2971-03d2-425c-9759-3a6e79a0b5c6.png)

**Comment by manchuck** [comment]
@szyrelle290612 I heard of this issue from another developer. After debugging, it looks like the key was copied incorrectly and added extra `\n` to the keys (this was on windows). Can you please check that the key is correct for creating a JWT token. 

You can use the `jsonwebtoken` or `jwt.io` to test out the keys.

**Comment by manchuck** [comment]
@AlbertVilaCardoHealth We are just passing the private key information along into the `jsonwebtoken` package. 

https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/jwt/lib/jwt.ts#L25

If you can run a test where you import the `jsonwebtoken` package and pass along your key information, do you get the same error?

**Comment by AlbertVilaCardoHealth** [comment]
@manchuck yes, my problem is not in your SDK, but on the [jsonwebtoken library](https://github.com/auth0/node-jsonwebtoken). Here's the line: https://github.com/auth0/node-jsonwebtoken/blob/e1fa9dcc12054a8681db4e6373da1b30cf7016e3/sign.js#L124

I updated my comment above so that it's more clear the situation I had. It's very specific to our setup.

**Comment by jnsdrssn** [comment]
Using Next.js I am facing the same issue, Key has no extra \n in it. Issue still persists.
