### ISSUE TITLE
CLI enable environment selection

### ISSUE THREAD

**Issue by ramzeaslan** [Vonage/vonage-node-sdk#93]
I would like to be able to define what environment the CLI should be working against currently it seems hardcoded to only work with Production env

A good solutions is is an argument which can be set as part of command

so for exmaple to check your balance, you would do :

> nexmo balance --host "URL"
18.96 EUR

**Comment by cbetta** [comment]
@ramzeaslan great idea. Would the host url be a full url, or just a domain, or also a port? Would this url be predictable? If so can we just do `nexmo balance --host dev`?

**Comment by leggetter** [comment]
@cbetta I think it'll be a `host`, probably including scheme e.g. `http://internal-api.nexmo.com`

**Comment by ramzeaslan** [comment]
@leggetter and @cbetta , I reckon having the full host makes the most sense, otherwise we are restricting ourselves and as such are less future proof.

Another alternative which is worth considering is that as part of the setup of the Nexmo CLI you are required to set your API key and Secret, what if you also set your env as part of the setup? 

Thanks

**Comment by cbetta** [comment]
@ramzeaslan interesting. Does make things easier to use. Let me think about it.

**Comment by leggetter** [comment]
It feels like we're moving more towards a per-project config rather than global config that you'll have to change as you move between environments.

IMO https://github.com/Nexmo/nexmo-cli/issues/109 could be a related to this. How nexmo-node enables it is a good question. But this discussion is really related to the CLI rather than nexmo-node.

To enable this we just need to make the `host` configurable within nexmo-node.

**Comment by cbetta** [comment]
I had not even noticed this issue wasn't on the CLI project. Let's close this one and re-open on the CLI library.

**Comment by cbetta** [comment]
Closing, have opened https://github.com/Nexmo/nexmo-cli/issues/114 instead.
