### ISSUE TITLE
[Bug]: wrong format for NCCOActions.CONNECT WebsocketEndpoint contentType

### ISSUE THREAD

**Issue by DecathectZero** [Vonage/vonage-node-sdk#958]
### Node Version

20.x

### Platform

Mac (Apple Silcon)

### SDK Version

3.17.0

### Code Sample

this should actually be `content-type`:
https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/voice/lib/types/Endpoint/WebsocketEndpoint.ts#L15-L18

It doesn't serialized from `contentType` to `content-type` anywhere so it gets completely ignored:
https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/voice/lib/classes/NCCO/Connect.ts#L104-L116

So if I try to do:
```
  async answer(....): Promise<NCCOAction[]> {
    return [
      {
        action: NCCOActions.CONNECT,
        from,
        endpoint: [
          {
            type: 'websocket',
            uri: `wss://${req.get('host')}/vonage/socket`,
            contentType: 'audio/l16;rate=8000'
          }
        ],
      },
    ];
  }
```
either allow `content-type` or serialize `CallEndpoint`

### Expected Behavior

the setting should be applied upon connection to a WS server.

### Actual Behavior

it actually won't get sent over, just gets ignored

**Comment by manchuck** [comment]
@DecathectZero Sorry to hear about this problem. In the Node SDK, we convert all keys to `camelCase` to make it easier to work with. Before making the call to the API, the SDK _should_ convert the casing to what the API wants (not all our endpoints use the same casing due to historical reasons). Can you provide me with an example of the SDK call so I can confirm the SDK is properly converting this NCCO command?

**Comment by manchuck** [comment]
I haven't heard back from @DecathectZero , If you are still having an issue, please re-open this
